pyston_lite: pass -fprofile-correction when PGO is enabled Seeing sometimes in the CI: aot_ceval.c: In function '_PyEval_EvalFrame_AOT_Interpreter': aot_ceval.c:9915:1: error: corrupted profile info: profile data is not flow-consistent  9915 | }       | ^ aot_ceval.c:9915:1: error: corrupted profile info: number of executions for edge 0-1806 thought to be -7
This flag should fix it:
-fprofile-correction

    Profiles collected using an instrumented binary for multi-threaded programs may be inconsistent due to missed counter updates. When this option is specified, GCC uses heuristics to correct or smooth out such inconsistencies. By default, GCC emits an error message when an inconsistent profile is detected.

    This option is enabled by -fauto-profile.